# Generated by Django 2.1 on 2019-07-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('original_url', models.URLField(null=True)),
                ('tiny_id', models.URLField(null=True)),
                ('total_hits', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
